//file:noinspection GrUnresolvedAccess
plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}
dependencies {
    minecraft("com.mojang:minecraft:${minecraft_version}")
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation("net.fabricmc:fabric-loader:${fabric_loader_version}")
    modImplementation("net.fabricmc.fabric-api:fabric-api:${fabric_version}")
    modImplementation("me.fzzyhmstrs:fzzy_config:${fzzy_config_version}")
    modApi("io.github.gameking1happy.gk1hcore:gk1hcore-fabric-1.21.1:${gk1hcore_version}")
    modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}")
    modRuntimeOnly("maven.modrinth:copper-recycling:${copper_recycling_version}+mod")
    modRuntimeOnly("maven.modrinth:diamond-recycling:${diamond_recycling_version}+mod")
    modRuntimeOnly("maven.modrinth:better-gold-recycling:${gold_recycling_version}+mod")
    modRuntimeOnly("maven.modrinth:better-iron-recycling:${iron_recycling_version}+mod")
    modRuntimeOnly("maven.modrinth:leather-recycling:${leather_recycling_version}+mod")
    modRuntimeOnly("maven.modrinth:netherite-recycling:${netherite_recycling_version}+mod")
    modRuntimeOnly("fuzs.puzzleslib:puzzleslib-fabric:${puzzleslib_version}")
    modRuntimeOnly("fuzs.iteminteractions:iteminteractions-fabric:${iteminteractions_version}")
    modImplementation("maven.modrinth:metal-bundles:v${metalbundles_version}-1.21.1-Fabric")
    modImplementation("maven.modrinth:enchanting-infuser:v${enchantinginfuser_version}-1.21.1-Fabric")
    modImplementation("maven.modrinth:netherite-extras:${netheriteextras_version}")
    modRuntimeOnly("io.wispforest:owo-lib:${owo_version}")
}
repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}