//file:noinspection GrUnresolvedAccess
//file:noinspection ForeignDelegate
plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.14-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.122' apply false
}
subprojects {
    repositories {
        maven {
            name = "FzzyMaven"
            url = "https://maven.fzzyhmstrs.me/"
        }
        maven {
            name = "Fuzs Mod Resources"
            url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
        }
        maven {
            name = "GK1H Mod Resources"
            url = "https://raw.githubusercontent.com/Gameking1happy-Development/Mod-Resources/main/maven/"
        }
        maven {
            name = "oωo (owo-lib)"
            url = "https://maven.wispforest.io/releases/" }
        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }
    }
}