# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=21.1.2.0
group=io.github.gameking1happy.gk1hrecycling
java_version=21
# Common
minecraft_version=1.21.1
mod_name=GK1H Recycling
mod_author=Gameking1happy Development
mod_id=gk1hrecycling
license=MIT
description=Add-on for notblue's recycling mods made by GK1H.
credits=jaredlll08: MultiLoader-Template; notblue
mod_source_url=https://github.com/Gameking1happy-Development/GK1H-Recycling
mod_issue_url=https://github.com/Gameking1happy-Development/GK1H-Recycling/issues
gk1hcore_version=21.1.2.2
gk1hrecipes_version=21.1.2.0
fzzy_config_version=0.7.3+1.21
modmenu_version=11.0.3
copper_recycling_version=2.4.1
diamond_recycling_version=1.3.4
gold_recycling_version=2.4.2
iron_recycling_version=3.5.2
leather_recycling_version=1.6.4
netherite_recycling_version=1.4.1
puzzleslib_version=21.1.39
iteminteractions_version=21.1.4
connector_version=2.0.0-beta.11+1.21.1
ffapi_version=0.115.6+2.1.4+1.21.1
connector_extras_version=1.12.1+1.21.1
metalbundles_version=21.1.1
enchantinginfuser_version=21.1.2
netheriteextras_version=0.4.0+mc1.21
owo_version=[VERSIONED]
minecraft_version_range=[1.21.1]
# This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17
# Fabric
fabric_version=0.116.7+1.21.1
fabric_loader_version=0.18.0
# NeoForge
neoforge_version=21.1.215
neoforge_loader_version_range=[1,)
# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
